/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/product': RouteRecordInfo<
      '/admin/product',
      '/admin/product',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkout': RouteRecordInfo<
      '/checkout',
      '/checkout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dev/components': RouteRecordInfo<
      '/dev/components',
      '/dev/components',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forbidden': RouteRecordInfo<
      '/forbidden',
      '/forbidden',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/forgot-password': RouteRecordInfo<
      '/forgot-password',
      '/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/product/[id]': RouteRecordInfo<
      '/product/[id]',
      '/product/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/profile/': RouteRecordInfo<
      '/profile/',
      '/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/reset-password': RouteRecordInfo<
      '/reset-password',
      '/reset-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/cart': RouteRecordInfo<
      '/user/cart',
      '/user/cart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/orders/': RouteRecordInfo<
      '/user/orders/',
      '/user/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/orders/[id]': RouteRecordInfo<
      '/user/orders/[id]',
      '/user/orders/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/verify-email': RouteRecordInfo<
      '/verify-email',
      '/verify-email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/product.vue': {
      routes:
        | '/admin/product'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/checkout.vue': {
      routes:
        | '/checkout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dev/components.vue': {
      routes:
        | '/dev/components'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/forbidden.vue': {
      routes:
        | '/forbidden'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/forgot-password.vue': {
      routes:
        | '/forgot-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/product/[id].vue': {
      routes:
        | '/product/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/profile/index.vue': {
      routes:
        | '/profile/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/reset-password.vue': {
      routes:
        | '/reset-password'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/cart.vue': {
      routes:
        | '/user/cart'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/orders/index.vue': {
      routes:
        | '/user/orders/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/user/orders/[id].vue': {
      routes:
        | '/user/orders/[id]'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/verify-email.vue': {
      routes:
        | '/verify-email'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
